#!/usr/bin/env bash
set -e

# Get the script's DIR
DIR=`dirname ${0}`;

# date command to use
DATEBIN=`which date`
# Python command to use
PYTHON_CMD="python"
# command to use to run manage.py
MANAGE="$PYTHON_CMD $DIR/app/django/manage.py"

function report_exit_status() {
    echo "** **** post_update script exiting with status: $? **** **"
}
# Call report_exit_status on exit
trap "report_exit_status" 0

# Redirect entire output to .lastrun file
# and also to syslog for ease of access by Dev Team, and persistence
exec > >(logger -p local6.notice -s 2>&1 | tee "$DIR/post_update.lastrun")
# Redirect stderr to stdout
exec 2>&1

# Print usage if no argument was passed
if [[ -z $1 ]]
then
    echo "usage: post_update CONTEXT_NAME"
    exit 1
fi

# Find all settings modules that include base_non_local
SETTINGS_MODULES=`grep -l '^from .base_non_local' $DIR/app/django/timetables/settings/*.py | while read f ; do basename $f .py ; done | xargs echo`

# Check that the supplied argument matches one of them
SETTINGS_MODULES_REGEXP=`echo $SETTINGS_MODULES | awk '{print "^\\\(" $0 "\\\)$" }' | sed -e 's/ /\\\|/g'`
ARG_VALIDATION_MATCHES=`echo $1 | grep $SETTINGS_MODULES_REGEXP 2>/dev/null | wc -l`

if [[ $ARG_VALIDATION_MATCHES -ne "1" ]]
then
    echo "Error: Unknown deployment context: $1"
    echo "CONTEXT_NAME must be one of: $SETTINGS_MODULES"
    exit 1
fi

# Set the DJANGO_SETTINGS_MODULE according to the first argument
export DJANGO_SETTINGS_MODULE=timetables.settings.$1
export REQUIREMENTS_FILE=$DIR/app/requirements/$1.txt

## Capture and time, and write to local file to try and show
## an approximate time the shell script was called.
NOW=`${DATEBIN} '+%Y%m%d %H:%M:%S'`
echo "** **** post_update script started at: $NOW **** **"
echo "** (output is also recorded in syslog local6 and post_update.lastrun) **" 


# Log the settings module being used
echo "** Using settings module: $DJANGO_SETTINGS_MODULE **"
echo "** Using requirements file: $REQUIREMENTS_FILE **"
echo ""

# Install required dependencies
echo "** Installing Python packages w/ pip **"
sudo pip install -r "$REQUIREMENTS_FILE"
echo ""

# The manage commands to run:
echo "** Running Django manage commands **"
$MANAGE syncdb --noinput || exit 2;
$MANAGE migrate --noinput || exit 3;
$MANAGE collectstatic  --noinput || exit 4;

# Restart apache
# Should we use sudo -n to never prompt for a pw?
echo "** Restarting apache **"
sudo /etc/init.d/apache2 restart || exit 5;

exit 0;
