#!/usr/bin/env python
import json
import csv
import sys

# This utility reads, from STDIN, a JSON file of the format generated by
# "manage.py dumpdata timetables" and extracts user permission data, outputting
# it in CSV format.
# This CSV output can then be inspected and edited if necessary, before being
# supplied to other utilities.
# CSV columns: Subject (fullpath), User (fullpath), User Data (e.g. 'salt')

input = json.load(sys.stdin)


def isModel(model):
    def customfilter(obj):
        return obj["model"] == model
    return customfilter


def isAdminAnnotation(obj):
    return obj["fields"]["annotation"] == "admin"

things = filter(isModel("timetables.thing"), input)
thingtags = filter(isModel("timetables.thingtag"), input)
adminthingtags = filter(isAdminAnnotation, thingtags)

pk2fullpath = {}
pk2userdata = {}

for thing in things:
    pk = thing["pk"]
    fullpath = thing["fields"]["fullpath"]
    userdata = thing["fields"]["data"]
    pk2fullpath[pk] = fullpath
    pk2userdata[pk] = userdata

perms = []

for thingtag in adminthingtags:
    # extract the "user, subject" pairs
    userthing = thingtag["fields"]["thing"]
    subjectthing = thingtag["fields"]["targetthing"]
    subjectpath = pk2fullpath[subjectthing]
    userpath = pk2fullpath[userthing]
    userdata = pk2userdata[userthing]
    perms.append((subjectpath, userpath, userdata))

output = sorted(perms, key=lambda perm: perm[1])
output.sort(key=lambda perm: perm[0])

writer = csv.writer(sys.stdout, dialect=csv.excel)
writer.writerows(output)
